nama = input("Masukkan nama:")
nim = input("Masukkan nim:")
kelas = input("Masukkan kelas:")
prodi = input("Masukkan prodi:")
print("-------------")
print("Biodata Mahasiswa")
print("-------------")
print("nama:",nama)
print("nim:",nim)
print("kelas:",kelas)
print("prodi:",prodi)
